#
# MacOS CI jobs
#

#
# Anchors
#

.macos-compiler-base:
  extends: .common-ci-base
  stage: compile
  tags:
    - macos-ci
  variables:
    !reference [.compiler-variables]
  script: !reference [.compiler-script]

.macos-test-base:
  extends: .common-ci-base
  stage: test
  tags:
    - macos-ci
  before_script:
    - |
      for file in $TEST_FILES; do
        curl -fLs "https://gitlab.com/AOMediaCodec/aom-testing/-/raw/master/test-files/$file.zst" | zstd -d - -o "$file"
      done

.macos-unit-test-base:
  extends: .macos-test-base
  variables:
    GTEST_OUTPUT: xml:report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
  needs:
    - macOS (Static, Tests)

#
# Compile jobs
#

macOS (Static, Tests):
  extends: .macos-compiler-base
  variables:
    CMAKE_GENERATOR: Xcode
  parallel:
    matrix:
      - CMAKE_GENERATOR: Xcode
      - CMAKE_GENERATOR: Ninja
        EXTRA_CMAKE_FLAGS: -DBUILD_TESTING=ON
        EXTRA_CFLAGS: -Wno-error -g
        EXTRA_CXXFLAGS: -Wno-error -g
        PREFIX_DIR: ${CI_PROJECT_DIR}/SVT-Install/
        TARGET: install
  artifacts:
    expire_in: 1 day
    paths:
      - Bin/Release/SvtAv1EncApp
      - Bin/Release/SvtAv1DecApp
      - Bin/Release/*
      - SVT-Install/*

#
# Test jobs
#

macOS Unit Tests:
  extends: .macos-unit-test-base
  parallel:
    matrix:
      - UNIT_TEST: SvtAv1UnitTests
        GTEST_TOTAL_SHARDS: 4
        GTEST_SHARD_INDEX: [0, 1, 2, 3]
      - UNIT_TEST: SvtAv1E2ETests
        SVT_AV1_TEST_VECTOR_PATH: $CI_PROJECT_DIR/test/vectors
  cache:
    key: testvectors
    paths:
      - test/vectors
    policy: pull-push
  script:
    - |
      if [ -n "$SVT_AV1_TEST_VECTOR_PATH" ]; then
        cmake -B Build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=ON
        cmake --build Build --target TestVectors
      fi
    - ./Bin/Release/$UNIT_TEST

macOS Enc Test:
  extends: .macos-test-base
  variables:
    TEST_FILES: akiyo_cif.y4m Chimera-Aerial_480x264_2997fps_10bit_420_150frames.y4m
  script: !reference [.enc-test-script]
  parallel: !reference [.enc-test-parallel]
  artifacts: !reference [.enc-test-artifacts]
  needs:
    - macOS (Static, Tests)

macOS FFmpeg (Static):
  extends: .macos-test-base
  stage: compile
  variables:
    CFLAGS: -pipe
    CXXFLAGS: -pipe
    LDFLAGS: -pipe
    GIT_DEPTH: 0
    PREFIX_DIR: ${CI_PROJECT_DIR}/SVT-Install/
  before_script:
    - !reference [.ffmpeg-before-script-clone]
    - !reference [.ffmpeg-before-script-export]
  script:
    - !reference [.ffmpeg-svtav1-script]
    - !reference [.ffmpeg-aom-script]
    - !reference [.ffmpeg-libvpx-script]
    - !reference [.ffmpeg-dav1d-script]
    - !reference [.ffmpeg-vmaf-script]
    # symbol conflict tests
    - |
      conflicts=$(
        nm -Ag --defined-only ${PREFIX_DIR}/lib/lib{SvtAv1Enc,aom,dav1d,vpx,vmaf}.a 2>/dev/null |
        cut -d' ' -f 4 |
        sort |
        uniq -d
      )
      if [ -n "$conflicts" ]; then
        printf 'Conflicts Found!\n'
        for conflict in $conflicts; do
          nm -Ag --defined-only ${PREFIX_DIR}/lib/lib{SvtAv1Enc,aom,dav1d,vpx,vmaf}.a 2>/dev/null |
          sort -k3 |
          grep -- " $conflict$"
        done
        exit 1
      fi
    - !reference [.ffmpeg-ffmpeg-script]
    - ccache -s
  artifacts:
    untracked: false
    expire_in: 30 days
    paths:
      - ffmpeg
